import { ThemeModeScript } from "flowbite-react";
import { DarkThemeToggle } from "flowbite-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeInit } from "../.flowbite-react/init";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flowbite React Template Next.js",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeInit />

        <main className="flex min-h-screen flex-col items-center justify-center bg-white px-4 py-24 dark:bg-gray-900">
          <div className="absolute inset-0 size-full">
            <div className="relative h-full w-full select-none">
            </div>
          </div>
          <div className="absolute top-4 right-4">
            <DarkThemeToggle />
          </div>

          <div className="relative flex w-full max-w-5xl flex-col items-center justify-center gap-12"> {children}</div>
        </main>
      </body>
    </html>
  );
}
